name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: sudo snap install ngrok
    - name: Auth
      run: sudo ngrok authtoken 1lM7ngNsY5LGFZLz5OVFrrKGO4V_6Zn2vX8aw9BwNb5mLSJkc

    - run: sudo apt-get -y install xrdp
    - run: sudo ufw allow 3389/tcp
    - run: sudo service xrdp start
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
