name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: sudo curl -fsSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -o ngrok.zip
    - name: Extract ngrok
      run: unzip ngrok.zip
    - name: Auth (using encrypted secret)
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable SSH
      run: sudo systemctl start ssh
    - name: Create User with Sudo (**HIGH SECURITY RISK)  **
      run: sudo useradd -m runneradmin && sudo echo "P@ssw0rd!" | sudo passwd runneradmin  # Creates user and sets weak password
    - name: Grant Sudo Access (**HUGE SECURITY RISK)**
      run: sudo usermod -aG sudo runneradmin  # Grants sudo access to user with weak password

    # **Strongly Consider SSH Key-Based Authentication Instead!**

    - name: Create Tunnel (expose port 22 for SSH)
      run: ./ngrok tcp 22
