name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: sudo snap install ngrok
    - name: Auth
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - run: sudo apt-get -y install xrdp
    - run: sudo ufw allow 3389/tcp
    - run: sudo service xrdp start
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
