name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: sudo curl -fsSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -o ngrok.zip
    - name: Extract ngrok
      run: unzip ngrok.zip
    - name: Auth (using encrypted secret)
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable SSH
      run: |
        echo "runner:P@ssw0rd!" | sudo chpasswd
        sudo systemctl start ssh
    - name: Allow Remote Login (**Security Risk - Consider Key-Based Authentication)
      run: echo "P@ssw0rd!" | sudo -S usermod -aG sudo runner  # Grant sudo access to user 'runner' (Security Risk)
    - name: Create Tunnel (expose port 22 for SSH)
      run: ./ngrok tcp 22
